language: node_js
script: npm test
node_js:
- node
- 4
- '0.12'
notifications:
  email: false
deploy:
  provider: npm
  email: npm@eli-white.com
  api_key:
    secure: Rw43WPxQdsnUl/Cuad0eksblKHP5+jehGjm/F2IPf8oH6yIBCeGxDZdiDyiVoeCzNr2Vuv7yxXubmVpxFNQbf/VfiPxGW+YEUx535LbFUSzIREsQlqMVms7Jh3TPB3LSNAZvfrWE2S9zns9K7fkGvox6ANmWvGE05BdAQDz/xPBQ4JKIsLqO45hPqf5PjVq8LXNvuyi7tiZmsseGPQgn4CfH6A8VXy7BfykimE+/GG4IBniwhC42Jo1Qn/8TBo4MWmnB3R04rremBSwptA+x7Hru8ocLN8o7Ytr5SdI5jt4o5pIYY+2BEPKkfB8T871kbWVdVIiiyJv94laJNAVCOEVICbuVmvwBlH6xSsTnrAmR3Tp6sZNesxYE6y3GxtbX+LC4xSk0p6Z3mI5IQP3bVgRoH8QcURcOxHSZcWhbW0zT+4iKq+kGGaDQkXU3Qob/u7RNPhzTPwxJ3gZmAlW/X8X9PQ6YjfEguFxD5uJKT3rb0p5oPsXIoIvk025R+ZdqxowDQdC4fWRzVp4h9yd2KovIE0TamJGWpDfNas4MikDKbGcGpNndWW3UT4fYSmI6SK/vrRoldVRJU7bJQm/gsaVgTWEc1CwYykf/ZOvVnJInANwD4rvq8Y6GUnLTV7lZNb4fUqj6Z1qRaQ1JKw/bOdlojfvT1F7sz22lEVjpWno=
  on:
    tags: true
    repo: TheSavior/babel-plugin-rewire-es5
    node: '0.12'
